### ISSUE TITLE
ppl read branch

### ISSUE THREAD

**Issue by frhodam** [gpagliuca/pyfas#18]
I am a newbie in using pyfas.

Actually i found something called bug i think if i have a branch named, for example, "FLEX. RISER", this branch will not be read by the module as a branch name.

I think the problem is in the regex pattern in _define_branch:
`def _define_branch(self, variable_idx):
return re.findall(r"'[\w\ \:\-]*'", \
                          self.profiles[variable_idx])[2].replace("'", "")`

I think it will be solved if the pattern is changed into:
`def _define_branch(self, variable_idx):
return re.findall(r"'[\w\ \:\-\.]*'", \
                          self.profiles[variable_idx])[2].replace("'", "")`

I am just adding a \. in the regex pattern.

**Comment by gpagliuca** [comment]
Fixed, thanks for spotting it

**Comment by frhodam** [comment]
Hi. Thank you for your response.
This is the first time i raised and issue on github.
Based on this, i think i should update the pyfas module, correct?
If so, is the updated module already available to be installed via pip?

**Comment by gpagliuca** [comment]
yes, updating pyfas you will get v0.4.1 with the hotfix applied.

Cheers

Il giorno ven 19 giu 2020 alle ore 02:41 frhodam <notifications@github.com>
ha scritto:
