### ISSUE TITLE
pressure temperature nesting issue in tab.py

### ISSUE THREAD

**Issue by kjeeetil** [gpagliuca/pyfas#20]
There is an issue which gives wrong values for pressure and temperature when reading a fixed format fluid table. The nesting when adding up the "long" pressures and temperature vectors are switched, looping through pressures then temperatures while it should be opposite.

this is the affected code:
array_ts = []
array_ps = []
for array_t, array_p in it.product(self.metadata["t_array"][0],
                                                    self.metadata["p_array"][0]):
            array_ts.append(array_t)
            array_ps.append(array_p/1e5)

i'm not familiar with how the "it.product" object above works (possibly you could just swap the arguments?), alternatively the code below produces the desired result in my case:
new_p=[]
new_t=[]
for p in self.metadata['p_array'][0]:
    new_t=new_t+list(self.metadata['t_array'][0])
    new_p=new_p+[p/1e5 for x in self.metadata['p_array'][0]]

Also thanks for making a great repository, very useful!

**Comment by gpagliuca** [comment]
thanks to you for spotting the issue. Would you have time and energy for a PR? If not do not worry, I'll handle that but I do not know when.

cheers

**Comment by kjeeetil** [comment]
I'll give it a shot!

**Comment by kjeeetil** [comment]
PR issued

**Comment by gpagliuca** [comment]
Just merged, thanks!

Giuseppe

Il giorno gio 27 mag 2021 alle ore 16:34 kjeeetil ***@***.***>
ha scritto:
