### ISSUE TITLE
tpl.py and view_trends

### ISSUE THREAD

**Issue by XT3V3** [gpagliuca/pyfas#24]
Problem
There's an error in the tpl file. When I use the view_trends function, the output for ID, VISG, VISHL and VISWT are messed up. As an example, for one of my cases the variable ID will show up as:
![bug](https://user-images.githubusercontent.com/103040127/163724258-ef8fe0f8-12d9-4a65-9b94-507470efcf80.PNG)

The correct output should be:
![fixed](https://user-images.githubusercontent.com/103040127/163724270-9b3274cf-cde9-466c-8bbf-a8d8f839a089.PNG)

Solution
If I change line 99 in the tpl.py file from:
`temp = [x[1:-1] for x in re.findall("\'[\w\(\) \-\:\/]+\'", st)]`
to:
`temp = [x[1:-1] for x in re.findall("\'[\w\(\) \=  \, \. \-\:\/]+\'", st)]`
the output will be correct.

**Comment by gpagliuca** [comment]
Hi, thanks! 
Would be possible for you to create a PR? A bit busy at the moment...

**Comment by XT3V3** [comment]
I'll do it.

**Comment by gpagliuca** [comment]
thanks! Just merged
